# -*- encoding: utf-8 -*-

module Territories
  Countries = [['United States', 'USA'],
              ['Canada', 'CAN'],
              ['--', ''],
              ['Afghanistan', 'AFG'],
              ['Åland Islands', 'ALA'],
              ['Albania', 'ALB'],
              ['Algeria', 'DZA'],
              ['American Samoa', 'ASM'],
              ['Andorra', 'AND'],
              ['Angola', 'AGO'],
              ['Anguilla', 'AIA'],
              ['Antarctica', 'ATA'],
              ['Antigua and Barbuda', 'ATG'],
              ['Argentina', 'ARG'],
              ['Armenia', 'ARM'],
              ['Aruba', 'ABW'],
              ['Australia', 'AUS'],
              ['Austria', 'AUT'],
              ['Azerbaijan', 'AZE'],
              ['Bahamas', 'BHS'],
              ['Bahrain', 'BHR'],
              ['Bangladesh', 'BGD'],
              ['Barbados', 'BRB'],
              ['Belarus', 'BLR'],
              ['Belgium', 'BEL'],
              ['Belize', 'BLZ'],
              ['Benin', 'BEN'],
              ['Bermuda', 'BMU'],
              ['Bhutan', 'BTN'],
              ['Bolivia', 'BOL'],
              ['Bonaire, Sint Eustatius and Saba', 'BES'],
              ['Bosnia and Herzegovina', 'BIH'],
              ['Botswana', 'BWA'],
              ['Bouvet Island', 'BVT'],
              ['Brazil', 'BRA'],
              ['British Indian Ocean Territory', 'IOT'],
              ['Brunei Darussalam', 'BRN'],
              ['Bulgaria', 'BGR'],
              ['Burkina Faso', 'BFA'],
              ['Burundi', 'BDI'],
              ['Cambodia', 'KHM'],
              ['Cameroon', 'CMR'],
              ['Canada', 'CAN'],
              ['Cape Verde', 'CPV'],
              ['Cayman Islands', 'CYM'],
              ['Central African Republic', 'CAF'],
              ['Chad', 'TCD'],
              ['Chile', 'CHL'],
              ['China', 'CHN'],
              ['Christmas Island', 'CXR'],
              ['Cocos (Keeling) Islands', 'CCK'],
              ['Colombia', 'COL'],
              ['Comoros', 'COM'],
              ['Congo', 'COG'],
              ['The Democratic Republic of the Congo', 'COD'],
              ['Cook Islands', 'COK'],
              ['Costa Rica', 'CRI'],
              ["Côte d'Ivoire", 'CIV'],
              ['Croatia', 'HRV'],
              ['Cuba', 'CUB'],
              ['Curaçao', 'CUW'],
              ['Cyprus', 'CYP'],
              ['Czech Republic', 'CZE'],
              ['Denmark', 'DNK'],
              ['Djibouti', 'DJI'],
              ['Dominica', 'DMA'],
              ['Dominican Republic', 'DOM'],
              ['Ecuador', 'ECU'],
              ['Egypt', 'EGY'],
              ['El Salvador', 'SLV'],
              ['Equatorial Guinea', 'GNQ'],
              ['Eritrea', 'ERI'],
              ['Estonia', 'EST'],
              ['Ethiopia', 'ETH'],
              ['Faeroe Islands', 'FRO'],
              ['Falkland Islands', 'FLK'],
              ['Fiji', 'FJI'],
              ['Finland', 'FIN'],
              ['France', 'FRA'],
              ['French Guiana', 'GUF'],
              ['French Polynesia', 'PYF'],
              ['French Southern Territories', 'ATF'],
              ['Gabon', 'GAB'],
              ['Gambia', 'GMB'],
              ['Georgia', 'GEO'],
              ['Germany', 'DEU'],
              ['Ghana', 'GHA'],
              ['Gibraltar', 'GIB'],
              ['Great Britain', 'GBR'],
              ['Greece', 'GRC'],
              ['Greenland', 'GRL'],
              ['Grenada', 'GRD'],
              ['Guadeloupe', 'GLP'],
              ['Guam', 'GUM'],
              ['Guatemala', 'GTM'],
              ['Guernsey', 'GGY'],
              ['Guinea', 'GIN'],
              ['Guinea-Bissau', 'GNB'],
              ['Guyana', 'GUY'],
              ['Haiti', 'HTI'],
              ['Heard Island and McDonald Islands', 'HMD'],
              ['Honduras', 'HND'],
              ['Hong Kong', 'HKG'],
              ['Hungary', 'HUN'],
              ['Iceland', 'ISL'],
              ['India', 'IND'],
              ['Indonesia', 'IDN'],
              ['Iran ', 'IRN'],
              ['Iraq', 'IRQ'],
              ['Ireland', 'IRL'],
              ['Isle of Man', 'IMN'],
              ['Israel', 'ISR'],
              ['Italy', 'ITA'],
              ['Ivory Coast', 'CIV'],
              ['Jamaica', 'JAM'],
              ['Japan', 'JPN'],
              ['Jersey', 'JEY'],
              ['Jordan', 'JOR'],
              ['Kazakhstan', 'KAZ'],
              ['Kenya', 'KEN'],
              ['Kiribati', 'KIR'],
              ["Korea, Democratic People's Republic of", 'PRK'],
              ['Korea, Republic of', 'KOR'],
              ['Kuwait', 'KWT'],
              ['Kyrgyzstan', 'KGZ'],
              ['Laos', 'LAO'],
              ['Latvia', 'LVA'],
              ['Lebanon', 'LBN'],
              ['Lesotho', 'LSO'],
              ['Liberia', 'LBR'],
              ['Libya', 'LBY'],
              ['Liechtenstein', 'LIE'],
              ['Lithuania', 'LTU'],
              ['Luxembourg', 'LUX'],
              ['Macao', 'MAC'],
              ['Macedonia', 'MKD'],
              ['Madagascar', 'MDG'],
              ['Malawi', 'MWI'],
              ['Malaysia', 'MYS'],
              ['Maldives', 'MDV'],
              ['Mali', 'MLI'],
              ['Malta', 'MLT'],
              ['Marshall Islands', 'MHL'],
              ['Martinique', 'MTQ'],
              ['Mauritania', 'MRT'],
              ['Mauritius', 'MUS'],
              ['Mayotte', 'MYT'],
              ['Mexico', 'MEX'],
              ['Micronesia', 'FSM'],
              ['Moldova', 'MDA'],
              ['Monaco', 'MCO'],
              ['Mongolia', 'MNG'],
              ['Montserrat', 'MSR'],
              ['Morocco', 'MAR'],
              ['Mozambique', 'MOZ'],
              ['Myanmar', 'MMR'],
              ['Namibia', 'NAM'],
              ['Nauru', 'NRU'],
              ['Nepal', 'NPL'],
              ['Netherlands', 'NLD'],
              ['Netherlands Antilles', 'ANT'],
              ['New Caledonia', 'NCL'],
              ['New Zealand', 'NZL'],
              ['Nicaragua', 'NIC'],
              ['Niger', 'NER'],
              ['Nigeria', 'NGA'],
              ['Niue', 'NIU'],
              ['Norfolk Island', 'NFK'],
              ['Northern Mariana Islands', 'MNP'],
              ['Norway', 'NOR'],
              ['Oman', 'OMN'],
              ['Pakistan', 'PAK'],
              ['Palau', 'PLW'],
              ['Palestinian Territories', 'PSE'],
              ['Panama', 'PAN'],
              ['Papua New Guinea', 'PNG'],
              ['Paraguay', 'PRY'],
              ['Peru', 'PER'],
              ['Philippines', 'PHL'],
              ['Pitcairn', 'PCN'],
              ['Poland', 'POL'],
              ['Portugal', 'PRT'],
              ['Puerto Rico', 'PRI'],
              ['Qatar', 'QAT'],
              ['Réunion', 'REU'],
              ['Romania', 'ROU'],
              ['Russia', 'RUS'],
              ['Rwanda', 'RWA'],
              ['Saint Barthélemy', 'BLM'],
              ['Saint Helena', 'SHN'],
              ['Saint Kitts and Nevis', 'KNA'],
              ['Saint Lucia', 'LCA'],
              ['Saint Martin', 'MAF'],
              ['Saint Pierre and Miquelon', 'SPM'],
              ['Saint Vincent and the Grenadines', 'VCT'],
              ['Samoa ', 'WSM'],
              ['San Marino', 'SMR'],
              ['Sao Tome and Principe', 'STP'],
              ['Saudi Arabia', 'SAU'],
              ['Senegal', 'SEN'],
              ['Serbia', 'SRB'],
              ['Seychelles', 'SYC'],
              ['Sierra Leone', 'SLE'],
              ['Sint Maarten', 'SXM'],
              ['Singapore', 'SGP'],
              ['Slovakia', 'SVK'],
              ['Slovenia', 'SVN'],
              ['Solomon Islands', 'SLB'],
              ['Somalia', 'SOM'],
              ['South Africa', 'ZAF'],
              ['South Georgia', 'SGS'],
              ['South Sudan', 'SSD'],
              ['Spain', 'ESP'],
              ['Sri Lanka', 'LKA'],
              ['Sudan', 'SDN'],
              ['Suriname', 'SUR'],
              ['Svalbard and Jan Mayen', 'SJM'],
              ['Swaziland', 'SWZ'],
              ['Sweden', 'SWE'],
              ['Switzerland', 'CHE'],
              ['Syrian Arab Republic', 'SYR'],
              ['Taiwan', 'TWN'],
              ['Tajikistan', 'TJK'],
              ['Tanzania', 'TZA'],
              ['Thailand', 'THA'],
              ['Timor-Leste', 'TLS'],
              ['Togo', 'TGO'],
              ['Tokelau', 'TKL'],
              ['Tonga', 'TON'],
              ['Trinidad and Tobago', 'TTO'],
              ['Tunisia', 'TUN'],
              ['Turkey', 'TUR'],
              ['Turkmenistan', 'TKM'],
              ['Turks and Caicos Islands', 'TCA'],
              ['Tuvalu', 'TUV'],
              ['Uganda', 'UGA'],
              ['Ukraine', 'UKR'],
              ['United Arab Emirates', 'ARE'],
              ['United Kingdom', 'GBR'],
              ['United States', 'USA'],
              ['Uruguay', 'URY'],
              ['Uzbekistan', 'UZB'],
              ['Vanuatu', 'VUT'],
              ['Vatican City', 'VAT'],
              ['Venezuela', 'VEN'],
              ['Vietnam', 'VNM'],
              ['Virgin Islands', 'VIR'],
              ['Wallis and Futuna', 'WLF'],
              ['Western Sahara', 'ESH'],
              ['Yemen', 'YEM'],
              ['Zambia', 'ZMB'],
              ['Zimbabwe', 'ZWE']]

  module US
    States = [['Alabama', 'AL'],
              ['Alaska', 'AK'],
              ['American Samoa', 'AS'],
              ['Arizona', 'AZ'],
              ['Arkansas', 'AR'],
              ['California', 'CA'],
              ['Colorado', 'CO'],
              ['Connecticut', 'CT'],
              ['Delaware', 'DE'],
              ['District of Columbia', 'DC'],
              ['Florida', 'FL'],
              ['Georgia', 'GA'],
              ['Guam', 'GU'],
              ['Hawaii', 'HI'],
              ['Idaho', 'ID'],
              ['Illinois', 'IL'],
              ['Indiana', 'IN'],
              ['Iowa', 'IA'],
              ['Kansas', 'KS'],
              ['Kentucky', 'KY'],
              ['Louisiana', 'LA'],
              ['Maine', 'ME'],
              ['Maryland', 'MD'],
              ['Marshall Islands', 'MH'],
              ['Massachusetts', 'MA'],
              ['Michigan', 'MI'],
              ['Minnesota', 'MN'],
              ['Mississippi', 'MS'],
              ['Missouri', 'MO'],
              ['Montana', 'MT'],
              ['Nebraska', 'NE'],
              ['Nevada', 'NV'],
              ['New Hampshire', 'NH'],
              ['New Jersey', 'NJ'],
              ['New Mexico', 'NM'],
              ['New York', 'NY'],
              ['North Carolina', 'NC'],
              ['North Dakota', 'ND'],
              ['Northern Marianas Islands', 'MP'],
              ['Ohio', 'OH'],
              ['Oklahoma', 'OK'],
              ['Oregon', 'OR'],
              ['Pennsylvania', 'PA'],
              ['Puerto Rico', 'PR'],
              ['Rhode Island', 'RI'],
              ['South Carolina', 'SC'],
              ['South Dakota', 'SD'],
              ['Tennessee', 'TN'],
              ['Texas', 'TX'],
              ['Utah', 'UT'],
              ['Vermont', 'VT'],
              ['Virginia', 'VA'],
              ['Virgin Islands', 'VI'],
              ['Washington', 'WA'],
              ['West Virginia', 'WV'],
              ['Wisconsin', 'WI'],
              ['Wyoming', 'WY']]
  end

  module Canada
    Provinces = [['Alberta', 'AB'],
                 ['British Columbia', 'BC'],
                 ['Manitoba', 'MB'],
                 ['New Brunswick', 'NB'],
                 ['Newfoundland and Labrador', 'NL'],
                 ['Northwest Territories', 'NT'],
                 ['Nova Scotia', 'NS'],
                 ['Nunavut', 'NU'],
                 ['Ontario', 'ON'],
                 ['Prince Edward Island', 'PE'],
                 ['Quebec', 'QC'],
                 ['Saskatchewan', 'SK'],
                 ['Yukon', 'YT']]
  end
end
